version: "3.9"

services:
  backend:
    build: ./backend
    container_name: cctv-backend
    restart: always
    env_file:
      - backend/.env
    networks:
      - cctv-net

  frontend:
    build: ./frontend
    container_name: cctv-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - cctv-net

networks:
  cctv-net:
    driver: bridge
